### PR TITLE
Feat/update route

### PR DESCRIPTION
**Pull request by ramon-reichert**
I've started this branch from #16 (feat/list_ordering) to use the changes made there. But here in the PR I'm trying to merge with main as base. Is that ok?
And we must conclude that PR before to this one make sense, is it right?

### CODE REVIEW

**Comment by cesarFuhr** [comment]
If you rely on code from the other PR/branch you should merge the other one first.

**Comment by cesarFuhr** [comment]
This branch PR will be way more readable if you `rebase` this branch against `main`.
Let me know if you need any help doing that.

**Comment by cesarFuhr** [comment]
Please recreate this PR... we are having that weird bug where GitHub shows things that are not changed as changed.

**Comment by ramon-reichert** [comment]
Recreating in 3, 2, 1...

**Pull request closed without merging**
