### PR TITLE
Feat/http tests

### PR DESCRIPTION
**Pull request by ramon-reichert**

### CODE REVIEW

**Comment by ramon-reichert** [comment]
@cesarFuhr  Any comments until here?

**Comment by cesarFuhr** [comment]
This looks good, I would ask you to change this in two ways:
1 - Use directly the handle functions, it will simplify the code without loosing coverage.
2 - Assert that the JSON response (in the routes that do respond something) are being correctly written to the response body.

**Comment by ramon-reichert** [comment]
> 1 - Use directly the handle functions, it will simplify the code without loosing coverage. 

To directly call the handle function I had to export it. Isn't that right, right??
Furthermore, this way we do not test the http route itself, like I left at comments...

I think I'm loosing something...

**Comment by ramon-reichert** [comment]
> 2 - Assert that the JSON response (in the routes that do respond something) are being correctly written to the response body.

I'll move on to implement this change, while waiting your help on the previous topic.

**Comment by cesarFuhr** [comment]
Ok, its not unusual to have the handler functions in a separate package, then you would have to export them anyway.
You may have a single server to several APIs that use different set of handlers, that's when you need to test them separately.

You know what, keep it as it was, with the tests calling the server. Where did you got that idea? (its a good one :+1: )

**Comment by cesarFuhr** [comment]
Please try to clean up the PR, all the changes from the previous one are being listed here.
Why didn't you branched off `main` when you started this piece of work?

**Comment by ramon-reichert** [comment]
> Ok, its not unusual to have the handler functions in a separate package, then you would have to export them anyway. You may have a single server to several APIs that use different set of handlers, that's when you need to test them separately.
> 
> You know what, keep it as it was, with the tests calling the server. Where did you got that idea? (its a good one 👍 )

It's not my idea. Thats what I've understood from the reference you gave me: 
https://quii.gitbook.io/learn-go-with-tests/build-an-application/http-server

I'll keep this way, so.

**Comment by ramon-reichert** [comment]
> Please try to clean up the PR, all the changes from the previous one are being listed here. Why didn't you branched off `main` when you started this piece of work?

Sorry, I forgot. It's because I've started this ticket while the previous one was not merged yet. And after the merged, I forgot to rebase.

**Comment by ramon-reichert** [comment]
I've tried to clean up the commits, but its a mess. I'll open another PR.

**Comment by ramon-reichert** [comment]
I've tried to clean up the commits, but its a mess. I'll open another PR.

**Pull request closed without merging**
